# Generated by Django 3.1.2 on 2020-10-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20201024_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=255, null=True, verbose_name="User's lastname"),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, null=True, verbose_name='@username'),
        ),
    ]
