# Generated by Django 3.1.2 on 2020-10-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_auto_20201025_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='user_id',
            new_name='user',
        ),
    ]
